[build]
  # 일반적으로 build 단계에서는 의존성 설치 + 앱 빌드 스크립트를 실행합니다.
  # 단순 함수만 쓰면 command 없이도 됩니다. (원하면 npm ci 권장)
  functions = "netlify/functions"
  command = "npm install"

# ← 중요: Functions 설정은 [functions] 섹션에 둡니다.
[functions]
  external_node_modules = ["@netlify/blobs", "@netlify/runtime-utils"]